name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Install dotnet-ef tool
      run: |
        dotnet tool install --global dotnet-ef
        echo "::add-path::$(dotnet --info | grep 'Base Path' | cut -d ' ' -f 3)/dotnet-tools"

    - name: Restore dependencies
      run: dotnet restore src/PipelineApp/PipelineApp.csproj

    - name: Build the application
      run: dotnet build src/PipelineApp/PipelineApp.csproj --configuration Release

    - name: Apply Database Migrations
      run: dotnet ef database update --project src/PipelineApp/PipelineApp.csproj --configuration Release

    - name: Publish the application
      run: dotnet publish src/PipelineApp/PipelineApp.csproj --configuration Release --output ./publish

    - name: Deploy to production
      run: echo "Deploying to production..."